### ISSUE TITLE
what's the meaning of the number(200,300) in the file ''glove.840B.300d.txt''?

### ISSUE THREAD

**Issue by n2meetu** [HughWen/atae_lstm_wen#1]
![image](https://user-images.githubusercontent.com/22144058/38914604-95e0cd86-4312-11e8-85e5-6bcb3f309928.png)
1.  I am confused with the number "200"?  what does it represent ?
2. Does '300' means the word embedding's Dimension？

**Comment by markwwen** [comment]
Sorry to reply so late, the "200" means there are 200 words in this file. And "300" is the dimension of the word embedding.

**Comment by n2meetu** [comment]
Thank you vary much!Now I understand

**Comment by markwwen** [comment]
🙃 @n2meetu
